# Default image (https://hub.docker.com/_/microsoft-dotnet-core-sdk/)
image: mcr.microsoft.com/dotnet/framework/sdk:4.8

stages:
  - build
  - test

before_script:
  - dotnet --version

# Build
    
build_project:
  stage: build
  tags: [windows]
  script:
    - dotnet build TowerDefense.sln

# Test
test_model:
  stage: test
  tags: [windows]
  script:
    - dotnet test TowerDefenseTest
